# config.example.yaml
# Main configuration for md-to-pdf.

# --- Global Settings ---

# pdf_viewer: Command to open PDFs after generation (e.g., "xdg-open", "evince", "firefox").
# Set to null or comment out to disable auto-opening.
pdf_viewer: xdg-open # null

# global_pdf_options: Default Puppeteer PDF options.
# See https://pptr.dev/api/puppeteer.pdfoptions for all available options.
global_pdf_options:
  format: "Letter" # Common paper sizes: Letter, Legal, A3, A4, A5, etc.
  printBackground: true # Print background graphics.
  margin: # Page margins (units: px, in, cm, mm).
    top: "1in"
    right: "1in"
    bottom: "1in"
    left: "1in"
  # displayHeaderFooter: false # Set to true to enable header/footer.
  # headerTemplate: "<div>Header: Page <span class='pageNumber'></span> of <span class='totalPages'></span></div>"
  # footerTemplate: "<div>Footer: {{ .author }} - {{ .CurrentDateISO }}</div>"
  # anchor_options: # Options for markdown-it-anchor.
  #   level: [1, 2, 3, 4, 5, 6]
  #   permalink: false

# global_remove_shortcodes: Array of regex patterns (strings) to remove content globally.
global_remove_shortcodes:
  - "" # Example: "" to remove HTML comments.

# --- Math Rendering Settings (KaTeX) ---
math:
  enabled: true     # true to enable math rendering, false to disable.
  engine: "katex"   # Currently only "katex" is supported.
  # Options for KaTeX: https://katex.org/docs/options.html
  katex_options:
    throwOnError: false # false: renders errors as LaTeX source; true: throws error.
    trust: false        # SECURITY: false is recommended. Set to true only if Markdown source is fully trusted.
    # macros:           # Define custom LaTeX macros.
    #   "\\RR": "\\mathbb{R}"
    #   "\\boldvec": "\\mathbf{#1}"

# --- Document Type Plugin Registrations ---
# Maps a "plugin name" (used with --plugin) to its configuration file path.
# Paths are relative to this main config.yaml file's location.
document_type_plugins:
  default: "./plugins/default/default.config.yaml"
  cv: "./plugins/cv/cv.config.yaml"
  cover-letter: "./plugins/cover-letter/cover-letter.config.yaml"
  recipe: "./plugins/recipe/recipe.config.yaml"
  recipe-book: "./plugins/recipe-book/recipe-book.config.yaml"
  advanced-card: "./examples/custom_plugin_showcase/advanced-card/advanced-card.config.yaml"
  # Example for a custom plugin:
  # my-custom-plugin: "path/to/my/custom-plugins/my-plugin/my-plugin.config.yaml"

# --- Hugo Export Each Command Specific Configuration --- Section Removed ---
