# config.example.yaml
# Main configuration for md-to-pdf.

# --- Global Settings ---

# pdf_viewer: Command to open PDFs after generation (e.g., "xdg-open", "evince", "firefox").
# Set to null or comment out to disable auto-opening.
pdf_viewer: xdg-open

# global_pdf_options: Default Puppeteer PDF options.
# See https://pptr.dev/api/puppeteer.pdfoptions for all available options.
global_pdf_options:
  format: "Letter"
  printBackground: true
  margin:
    top: "1in"
    right: "1in"
    bottom: "1in"
    left: "1in"

# global_remove_shortcodes: Array of regex patterns to remove content globally.
global_remove_shortcodes:
  - ""

# --- Math Rendering Settings (KaTeX) ---
math:
  enabled: true
  engine: "katex"
  katex_options:
    throwOnError: false
    trust: false
    macros:
      "\\RR": "\\mathbb{R}"

# --- Global Parameters for Placeholders (`params`) ---
# Reusable key-value pairs merged with document front matter.
# params:
#   authorInfo:
#     name: "Default Author"
#     email: "contact@example.com"

# --- Collections Root Directory (Optional) ---
# Overrides the default location for storing managed plugin collections.
# Precedence: --coll-root > env var > this key > OS default.
# collections_root: "~/my-md-to-pdf-collections"

# --- Plugin Management Notes ---
# Bundled plugins (default, cv, recipe, etc.) are now auto-discovered.
# Custom plugins should be managed via the CLI:
#   - md-to-pdf collection add <git-url-or-path>
#   - md-to-pdf plugin add <local-plugin-path>
#
# Use `md-to-pdf config --plugin <name>` to see a plugin's final settings.

# --- Inline Plugin Overrides ---
# Override settings for any registered or bundled plugin.
# cv: # This 'cv' matches a bundled plugin
#   description: "My Custom CV Style"
#   pdf_options:
#     format: "A5"
