# examples/screenshot-config.yaml
# Configuration for generating screenshots.
# Paths are relative to this config file's location (the 'examples/' directory).

document_type_plugins:

  # --- ../README.md ---
  recipe: "../plugins/recipe/recipe.config.yaml"
  cv: "../plugins/cv/cv.config.yaml"
  cover-letter: "../plugins/cover-letter/cover-letter.config.yaml"
  
  # --- ../docs/plugin-management.md ---
  business-card: "../test/custom_plugins/business-card/business-card.config.yaml"
  advanced-card: "./custom_plugin_showcase/advanced-card/advanced-card.config.yaml"

