# scripts/linting/config.yaml

# --- Code ---
# scripts/linting/code/remove-auto-doc.js
remove-auto-doc:
  targets:
    - cli.js
    - index.js
    - src
    - test/e2e
    - test/integration
  excludes:
    - .mocharc.js
    - "test/scripts/**"
    - "scripts/**"
  excludeDirs:
    - assets
    - node_modules
    - test/scripts
    - scripts
# scripts/linting/code/logging-lint.js
logging:
  targets:
    - src
    - "*.js"
    - test/e2e
    - test/integration
  excludes:
    - "node_modules/**"
    - ".git/**"
    - src/utils/logger.js
    - "scripts/**"
    - "test/scripts/**"
    - "plugins/**"
# scripts/linting/code/standardize-js-line-one-all.js
standardize-line-one:
  targets:
    - "src/**/*.js"
    - "test/**/*.js"
    - "scripts/**/*.js"
  excludes:
    - "node_modules/**"
    - "scripts/shared/**"
    - "plugins/**"
    - "test/fixtures/**"
# scripts/linting/code/strip-trailing-whitespace.js
remove-ws:
  targets:
    - "src/**/*.js"
    - "test/**/*.js"
    - "scripts/**/*.js"
    - "plugins/**/*.js"
    - "*.js"
    - "*.sh"
  excludes:
    - "node_modules/**"
    - "scripts/shared/**"
    - "plugins/**/.contract/**"
    - "test/fixtures/**"
# scripts/linting/code/no-relative-paths.js
no-relative-paths:
  targets:
    - "src/**/*.js"
    #- "test/**/*.js"
    #- "plugins/**/*.js"
    #- "scripts/**/*.js"
    # fix these in batches
    - "scripts/linting/**/*.js"
    - "*.js"
  excludes:
    - "node_modules/**"
    - ".git/**"
    - "scripts/shared/**"
    - "plugins/**"
    - "test/fixtures/**"
    - "paths.js"
    - "scripts/scriptsPaths.js"


# --- Validators ---
# scripts/linting/validators/mocha-path-validator.js
validate-mocha:
  excludes: []
# scripts/linting/validators/paths-js-validator.js
validate-paths:
  ignores:
    - config.yaml
# scripts/linting/validators/paths-usage-validator.js
validate-paths-usage:
  targets:
    - "src"
    - "scripts"
    - "test"
    - "*.js"
  ignores:
    - "node_modules/**"
    - ".git/**"
    - "scripts/shared/**"
    - "plugins/**"
    - "test/fixtures/**"
    #- "paths.js"
    #- "scripts/scriptsPaths.js"

# --- Docs ---
# scripts/linting/docs/update-project-indices.js
update-indices:
  docs:
    indexFile: docs/index.md
    scanRoot: "docs"
    fileExtensions:
      - ".md"
    excludePatterns:
      - docs/dream-board.md
      - "docs/images/**"
    marker: "etc"
  plugins:
    indexFile: plugins/index.md
    scanRoot: "plugins"
    fileExtensions:
      - ".md"
    excludePatterns:
      - "plugins/**/index.md"
      - "plugins/**/*-example.md"
    marker: "plugins"
  scripts:
    indexFile: scripts/index.md
    scanRoot: "scripts"
    fileExtensions:
      - ".js"
      - ".sh"
      - ".mjs"
    excludePatterns:
      - "scripts/scriptsPaths.js"
      - "scripts/linting/**"
    marker: "scripts"
  linting:
    indexFile: scripts/linting/index.md
    scanRoot: scripts/linting
    fileExtensions:
      - ".js"
      - ".sh"
    excludePatterns: []
    marker: "linting"
  test-scripts:
    indexFile: test/index.md
    scanRoot: 
      - test/docs
      - test/scripts
    fileExtensions:
      - .js
      - .md
    excludePatterns: [] 
    marker: "test-scripts"
# scripts/linting/docs/postman.js
doc-links:
  excludes:
    - "node_modules/**"
    - ".git/**"
    - "assets/**"
    - "docs/archive/**"
    - "**/test/fixtures/**"
  allowed_extensions:
    - ".md"
    - ".js"
    - ".mjs"
  skip_link_patterns:
    - "**/my[-_]*"
    - "**/my[-_]*/**"
    - "**/sample.md"
    - "**/index.js"
    - "paths.js"

# --- Harness Configuration ---
harness:
  continueOnError: false
  steps:
    # --- Code ---
    - key: 'remove-ws'
      label: 'Code: Strip Trailing Whitespace'
      scriptPath: scripts/linting/code/strip-trailing-whitespace.js
      fix: true
    - key: 'standardize-line-one'
      label: 'Code: Standardize File Headers'
      scriptPath: scripts/linting/code/standardize-js-line-one-all.js
      ignoreFailure: true
    - key: 'logging'
      label: 'Code: Check for console/chalk usage'
      scriptPath: scripts/linting/code/logging-lint.js
    - key: 'remove-auto-doc' 
      label: 'Code: Check for auto-doc comments'
      scriptPath: scripts/linting/code/remove-auto-doc.js
    - key: no-relative-paths
      label: 'Code: Check for relative paths'
      scriptPath: scripts/linting/code/no-relative-paths.js

    # --- Validators ---
    - key: 'validate-mocha' 
      label: 'Validator: Check .mocharc.js paths'
      scriptPath: scripts/linting/validators/mocha-path-validator.js
    - key: 'validate-paths' 
      label: 'Validator: Check paths.js'
      scriptPath: scripts/linting/validators/paths-js-validator.js
    - key: 'validate-paths-usage' 
      label: 'Validator: Check paths usage'
      scriptPath: scripts/linting/validators/paths-usage-validator.js

    # --- Docs ---
    - key: 'update-indices' 
      label: 'Docs: Update Project Indices (Librarian)'
      scriptPath: scripts/linting/docs/update-project-indices.js
    - key: 'doc-links' 
      label: 'Docs: Check Markdown Links (Postman)'
      scriptPath: scripts/linting/docs/postman.js

    # --- Harness ---
    - key: 'eslint' 
      label: 'ESLint'
      quiet: false
      command: 'eslint'
      defaultTargets: ['.']

