# scripts/linting/config.yaml

# --- Global ---

# Add more excludes as needed
# excludes:
#   - "node_modules/**"

# --- Code ---

autoDoc:
  targets:
    - cli.js
    - index.js
    - src
    - test/e2e
    - test/integration
  excludes:
    - .mocharc.js
    - "test/scripts/**"
    - "scripts/**"
  excludeDirs:
    - assets
    - node_modules
    - test/scripts
    - scripts

logging:
  targets:
    - src
    - "*.js"
    - test/e2e
    - test/integration
  excludes:
    - "node_modules/**"
    - ".git/**"
    - src/utils/logger.js
    - "scripts/**"
    - "test/scripts/**"
    - "plugins/**"
    # Add more excludes as needed

standardizeJsLineOneAll:
  targets:
    - "src/**/*.js"
    - "test/**/*.js"
    - "scripts/**/*.js"
  excludes:
    - "node_modules/**"
    - "scripts/shared/**"
    - "plugins/**"
    - "test/fixtures/**"

stripTrailingWhitespace:
  targets:
    - "src/**/*.js"
    - "test/**/*.js"
    - "scripts/**/*.js"
    - "plugins/**/*.js"
    - "*.js"
    - "*.sh"
  excludes:
    - "node_modules/**"
    - "scripts/shared/**"
    - "plugins/**/.contract/**"
    - "test/fixtures/**"

# --- Validators ---

mochaPathValidator:
  excludes: []

pathsJsValidator:
  ignores:
    - config.yaml

# --- Docs ---

librarian:
  docs:
    indexFile: "docs/index.md"
    scanRoot: "docs"
    fileExtensions:
      - ".md"
    excludePatterns:
      - "docs/dream-board.md"
      - "docs/images/**"
    marker: "etc"

  plugins:
    indexFile: "plugins/index.md"
    scanRoot: "plugins"
    fileExtensions:
      - ".md"
    excludePatterns:
      - "plugins/**/index.md"
      - "plugins/**/*-example.md"
    marker: "plugins"

  scripts:
    indexFile: "scripts/index.md"
    scanRoot: "scripts"
    fileExtensions:
      - ".js"
      - ".sh"
      - ".mjs"
    excludePatterns:
      - "scripts/refactor/**"
    marker: "scripts"

  refactor-scripts:
    indexFile: "scripts/refactor/index.md"
    scanRoot: "scripts/refactor"
    fileExtensions:
      - ".js"
      - ".sh"
    excludePatterns: []
    marker: "scripts"

  test-scripts:
    indexFile: "test/index.md"
    scanRoot: 
      - "test/docs"
      - "test/scripts"
    fileExtensions:
      - ".js"
      - ".md"
    excludePatterns: [] 
    marker: "test-scripts"

postman:
  excludes:
    - "node_modules/**"
    - ".git/**"
    - "assets/**"
    - "docs/archive/**"
    - '**/test/fixtures/**'

  allowed_extensions:
    - ".md"
    - ".js"
    - ".mjs"

  # Patterns for filenames to skip auto-linking (tick or link)
  skip_link_patterns:
    - "**/my[-_]*"
    - "**/my[-_]*/**"
    - "**/sample.md"
    - "**/index.js"

