# scripts/linting/config.yaml

# --- Global ---

# excludes:
#   - "node_modules/**"

# --- Code ---
remove-auto-doc:
  targets:
    - cli.js
    - index.js
    - src
    - test/e2e
    - test/integration
  excludes:
    - .mocharc.js
    - "test/scripts/**"
    - "scripts/**"
  excludeDirs:
    - assets
    - node_modules
    - test/scripts
    - scripts

logging:
  targets:
    - src
    - "*.js"
    - test/e2e
    - test/integration
  excludes:
    - "node_modules/**"
    - ".git/**"
    - src/utils/logger.js
    - "scripts/**"
    - "test/scripts/**"
    - "plugins/**"

standardize-line-one:
  targets:
    - "src/**/*.js"
    - "test/**/*.js"
    - "scripts/**/*.js"
  excludes:
    - "node_modules/**"
    - "scripts/shared/**"
    - "plugins/**"
    - "test/fixtures/**"

remove-ws:
  targets:
    - "src/**/*.js"
    - "test/**/*.js"
    - "scripts/**/*.js"
    - "plugins/**/*.js"
    - "*.js"
    - "*.sh"
  excludes:
    - "node_modules/**"
    - "scripts/shared/**"
    - "plugins/**/.contract/**"
    - "test/fixtures/**"

# --- Validators ---
validate-mocha:
  excludes: []

validate-paths:
  ignores:
    - config.yaml

# --- Docs ---
update-indices:
  docs:
    indexFile: docs/index.md
    scanRoot: "docs"
    fileExtensions:
      - ".md"
    excludePatterns:
      - docs/dream-board.md
      - "docs/images/**"
    marker: "etc"
  plugins:
    indexFile: plugins/index.md
    scanRoot: "plugins"
    fileExtensions:
      - ".md"
    excludePatterns:
      - "plugins/**/index.md"
      - "plugins/**/*-example.md"
    marker: "plugins"
  scripts:
    indexFile: scripts/index.md
    scanRoot: "scripts"
    fileExtensions:
      - ".js"
      - ".sh"
      - ".mjs"
    excludePatterns:
      - "scripts/refactor/**"
    marker: "scripts"
  refactor-scripts:
    indexFile: scripts/refactor/index.md
    scanRoot: scripts/refactor
    fileExtensions:
      - ".js"
      - ".sh"
    excludePatterns: []
    marker: "scripts"
  test-scripts:
    indexFile: test/index.md
    scanRoot: 
      - test/docs
      - test/scripts
    fileExtensions:
      - .js
      - .md
    excludePatterns: [] 
    marker: "test-scripts"

doc-links:
  excludes:
    - "node_modules/**"
    - ".git/**"
    - "assets/**"
    - "docs/archive/**"
    - "**/test/fixtures/**"
  allowed_extensions:
    - ".md"
    - ".js"
    - ".mjs"
  skip_link_patterns:
    - "**/my[-_]*"
    - "**/my[-_]*/**"
    - "**/sample.md"
    - "**/index.js"

# --- Harness Configuration ---
harness:
  continueOnError: false
  quiet: true
  steps:
    - key: 'remove-ws'
      label: 'Code: Strip Trailing Whitespace'
      scriptPath: scripts/linting/code/strip-trailing-whitespace.js
    - key: 'standardize-line-one'
      label: 'Code: Standardize File Headers'
      scriptPath: scripts/linting/code/standardize-js-line-one-all.js
      ignoreFailure: true
    - key: 'logging'
      label: 'Code: Check for console/chalk usage'
      scriptPath: scripts/linting/code/logging-lint.js
    - key: 'remove-auto-doc' 
      label: 'Code: Check for auto-doc comments'
      scriptPath: scripts/linting/code/remove-auto-doc.js
    - key: 'validate-mocha' 
      label: 'Validator: Check .mocharc.js paths'
      scriptPath: scripts/linting/validators/mocha-path-validator.js
    - key: 'validate-paths' 
      label: 'Validator: Check paths.js'
      scriptPath: scripts/linting/validators/paths-js-validator.js
    - key: 'update-indices' 
      label: 'Docs: Update Project Indices'
      scriptPath: scripts/linting/docs/update-project-indices.js
    - key: 'doc-links' 
      label: 'Docs: Check Markdown Links (Postman)'
      scriptPath: scripts/linting/docs/postman.js
    - key: 'eslint' 
      label: 'ESLint'
      quiet: false
      command: 'eslint'
      defaultTargets: ['.']

