# scripts/linting/linting-config.yaml

# These are hardcoded core ignore paths (already write-protected):
#
# excludes:
#   - "node_modules/**"
#   - ".git/**"
#   - "assets/**"
#   - "docs/archive/**"
#
# The following filetypes are automatically linted:
#
# filetypes: [".js", ".json", ".md", ".sh", ".yaml", ".txt"]
#
# If you set `filetypes: [".js"]`, *only* `.js` files will be linted.

# --- Code ---

# scripts/linting/code/remove-jsdoc.js
remove-jsdoc:
  group: code
  alias: jsdoc
  filetypes: [".js"]
  targets:
    - "."
  excludes: []

# scripts/linting/code/logging-lint.js
logging:
  alias: chalk
  group: code
  filetypes: [".js"]
  targets:
    - "."
  excludes: # []
    - src/utils/formatters

# scripts/linting/code/standardize-js-line-one-all.js
standardize-line-one:
  alias: line-one
  group: code
  filetypes: [".js"]
  targets:
    - "."
  excludes: []

# scripts/linting/code/strip-trailing-whitespace.js
remove-ws:
  alias: whitespace
  group: code
  filetypes: [".css", ".js", ".json", ".yaml"]
  targets: ["."]
  excludes: []

# scripts/linting/code/no-relative-paths.js
no-relative-paths:
  alias: paths
  group: code
  filetypes: [".js"]
  targets: ["."]
  excludes:
    - paths

# --- Validators ---

# scripts/linting/validators/mocha-path-validator.js
validate-mocha:
  alias: "mocha"
  group: "validators"

# --- Docs ---

# scripts/linting/docs/find-litter.js
find-litter:
  alias: "custodian"
  group: "docs"
  targets: ["."]
  excludes: []

# scripts/linting/docs/update-project-indices.js
update-indices:
  alias: "librarian"
  group: "docs"
  #rule for README.md
  docs:
    indexFile: docs/index.md
    scanRoot: docs
    filetypes: [".md"]
  plugins:
    marker: "plugins"
    indexFile: plugins/index.md
    scanRoot: plugins
    filetypes: [".md"]
    excludePatterns:
      - "plugins/**/index.md"
      - "plugins/**/*-example.md"
  scripts:
    marker: "scripts"
    indexFile: scripts/index.md
    scanRoot: scripts
    filetypes: [".js", ".sh"]
    excludePatterns:
      - "scripts/linting/**"
  linting:
    marker: "linting"
    indexFile: scripts/linting/index.md
    scanRoot: scripts/linting
    filetypes: [".js", ".yaml"]
    excludePatterns: []
  test-scripts:
    marker: "test-scripts"
    indexFile: test/index.md
    scanRoot:
      - test/docs
      - test/scripts
    filetypes: [".js", ".md"]
    excludePatterns: []
  paths:
    marker: "paths"
    indexFile: paths/index.md
    scanRoot: paths
    filetypes: [".js", ".yaml"]
    excludePatterns: []

# scripts/linting/docs/postman.js
doc-links:
  alias: "postman"
  group: "docs"
  targets:
   - "."
  filetypes: [".md", ".js"]
  skip_link_patterns:
    - "**/my[-_]*"
    - "**/my[-_]*/**"
    - "**/sample.md"
    - "**/index.js"
  excludes:
    - "test/docs/checklist-*.md"
    - "test/docs/audit-log.md"
    - "plugins/recipe-book/README.md"
    - "docs/logger-*.md"      # in development

# --- Harness Configuration ---
harness:
  continueOnError: false
  steps:
    # --- Code ---
    - key: 'remove-ws'
      label: 'Code: Strip Trailing Whitespace'
      scriptPath: scripts/linting/code/strip-trailing-whitespace.js
    - key: 'standardize-line-one'
      label: 'Code: Standardize File Headers'
      scriptPath: scripts/linting/code/standardize-js-line-one-all.js
    - key: 'logging'
      label: 'Code: Check for console/chalk usage'
      scriptPath: scripts/linting/code/logging-lint.js
    - key: 'remove-jsdoc'
      label: 'Code: Check for JSdoc comments'
      scriptPath: scripts/linting/code/remove-jsdoc.js
    - key: 'no-relative-paths'
      label: 'Code: Check for relative paths'
      scriptPath: scripts/linting/code/no-relative-paths.js

    # --- Validators ---
    - key: 'validate-mocha'
      label: 'Validator: Check .mocharc.js paths'
      scriptPath: scripts/linting/validators/mocha-path-validator.js

    # --- Docs ---
    - key: 'update-indices'
      label: 'Docs: Update Project Indices (Librarian)'
      scriptPath: scripts/linting/docs/update-project-indices.js
    - key: 'doc-links'
      label: 'Docs: Check Markdown Links (Postman)'
      scriptPath: scripts/linting/docs/postman.js
    - key: 'find-litter'
      label: 'Docs: Find Litter (Custodian)'
      scriptPath: scripts/linting/docs/find-litter.js

    # --- Harness ---
    - key: 'eslint'
      label: 'ESLint'
      quiet: false
      command: 'eslint'
      defaultTargets: ['.']
