# scripts/linting/linting-config.yaml

# --- Code ---

# scripts/linting/code/remove-auto-doc.js
remove-auto-doc:
  targets:
    - cli.js
    - index.js
    - src
    - test
    - plugins
    - scripts
    - paths
  excludes:
    - .mocharc.js
    - "scripts/shared/file-helpers.js"
    - "scripts/ai/ai-context-generator.js"
  excludeDirs:
    - assets
    - "node_modules"
    - ".git"

# scripts/linting/code/logging-lint.js
logging:
  targets:
    - cli.js
    - index.js
    - src
    - test/integration
    - test/e2e
  excludes:
    - "node_modules/**"
    - ".git/**"
    - src/utils/logger.js
    - "plugins/**"

# scripts/linting/code/standardize-js-line-one-all.js
standardize-line-one:
  targets:
    - "src/**/*.js"
    - "test/**/*.js"
    - "scripts/**/*.js"
    - "plugins/**/*.js"
    - "paths/generator.js"
  excludes:
    - "node_modules/**"
    - "plugins/**"

# scripts/linting/code/strip-trailing-whitespace.js
remove-ws:
  alias: "ws" # Added alias
  group: "code" # Added group
  targets:
    - "src/**/*.js"
    - "test/**/*.js"
    - "scripts/**/*.js"
    - "plugins/**/*.js"
    - "paths/**/*.js"
    - "*.js"
    - "*.sh"
  excludes:
    - "node_modules/**"
    - "plugins/**/.contract/**"

# scripts/linting/code/no-relative-paths.js
no-relative-paths:
  group: "code" # Added group
  targets:
    - cli.js
    - index.js
    - "src/**/*.js"
    - "scripts/**/*.js"
  excludes:
    - "node_modules/**"
    - ".git/**"
    - paths
    - "plugins/**"
    - "test/fixtures/**"

# --- Validators ---

# scripts/linting/validators/mocha-path-validator.js
validate-mocha:
  group: "validators" # Added group

# --- Docs ---

# scripts/linting/docs/update-project-indices.js
update-indices:
  alias: "librarian"
  group: "docs" # Added group
  docs:
    indexFile: docs/index.md
    scanRoot: "docs"
    fileExtensions:
      - ".md"
    excludePatterns:
      - docs/dream-board.md
  plugins:
    marker: "plugins"
    indexFile: plugins/index.md
    scanRoot: "plugins"
    fileExtensions:
      - ".md"
    excludePatterns:
      - "plugins/**/index.md"
      - "plugins/**/*-example.md"
  scripts:
    marker: "scripts"
    indexFile: scripts/index.md
    scanRoot: "scripts"
    fileExtensions:
      - ".js"
      - ".sh"
    excludePatterns:
      - "scripts/linting/**"
  linting:
    marker: "linting"
    indexFile: scripts/linting/index.md
    scanRoot: scripts/linting
    fileExtensions:
      - ".js"
      - ".sh"
    excludePatterns: []
  test-scripts:
    marker: "test-scripts"
    indexFile: test/index.md
    scanRoot:
      - test/docs
      - test/scripts
    fileExtensions:
      - .js
      - .md
    excludePatterns: []

# scripts/linting/docs/postman.js
doc-links:
  alias: "postman"
  group: "docs" # Added group
  excludes:
    - "node_modules/**"
    - ".git/**"
    - "assets/**"
    - "docs/archive/**"
    - "**/test/fixtures/**"
  allowed_extensions:
    - ".md"
    - ".js"
    - ".mjs"
  skip_link_patterns:
    - "**/my[-_]*"
    - "**/my[-_]*/**"
    - "**/sample.md"
    - "**/index.js"
# scripts/linting/docs/find-litter.js
find-litter:
  group: "docs" # Added group
  targets:
    - src
    - docs
    - plugins
    - scripts
    - test
    - paths
    - "*.js"
    - "*.md"
  excludes:
    - "node_modules/**"
    - ".git/**"
    - "docs/archive/**"
    - "plugins/template-basic/"
    - "**/linting-docs.manifest.js"

# --- Harness Configuration ---
harness:
  continueOnError: false
  steps:
    # --- Code ---
    - key: 'remove-ws'
      label: 'Code: Strip Trailing Whitespace'
      scriptPath: scripts/linting/code/strip-trailing-whitespace.js
      fix: true
    - key: 'standardize-line-one'
      label: 'Code: Standardize File Headers'
      scriptPath: scripts/linting/code/standardize-js-line-one-all.js
      ignoreFailure: true
    - key: 'logging'
      label: 'Code: Check for console/chalk usage'
      scriptPath: scripts/linting/code/logging-lint.js
    - key: 'remove-auto-doc'
      label: 'Code: Check for auto-doc comments'
      scriptPath: scripts/linting/code/remove-auto-doc.js
    - key: no-relative-paths
      label: 'Code: Check for relative paths'
      scriptPath: scripts/linting/code/no-relative-paths.js

    # --- Validators ---
    - key: 'validate-mocha'
      label: 'Validator: Check .mocharc.js paths'
      scriptPath: scripts/linting/validators/mocha-path-validator.js

    # --- Docs ---
    - key: 'update-indices'
      label: 'Docs: Update Project Indices (Librarian)'
      scriptPath: scripts/linting/docs/update-project-indices.js
    - key: 'doc-links'
      label: 'Docs: Check Markdown Links (Postman)'
      scriptPath: scripts/linting/docs/postman.js
    - key: 'remove-litter'
      label: 'Docs: Find Litter (Custodian)'
      scriptPath: scripts/linting/docs/find-litter.js

    # --- Harness ---
    - key: 'eslint'
      label: 'ESLint'
      quiet: false
      command: 'eslint'
      defaultTargets: ['.']
