# scripts/linting/linting-config.yaml

# These are hardcoded core ignore paths (already write-protected):
#
# excludes:
#   - "node_modules/**"
#   - ".git/**"
#   - "assets/**"
#   - "docs/archive/**"
#
# The following filetypes are automatically linted:
#
# filetypes: [".js", ".json", ".md", ".sh", ".yaml", ".txt"]
#
# If you set `filetypes: [".js"]`, *only* `.js` files will be linted.
#
# See
#   node scripts/linting/lib/find-lint-skips.js
# for multi-level excludes (line, block, file, directory).

# --- Code ---

# scripts/linting/code/no-jsdoc.js
no-jsdoc:
  group: code
  alias: jsdoc
  filetypes: [".js"]
  targets:
    - "."
  excludes: []

# scripts/linting/code/no-console.js
no-console:
  alias: logs
  group: code
  filetypes: [".js"]
  targets:
    - "."
  excludes: # []
    - src/utils/formatters

# scripts/linting/code/no-bad-headers.js
no-bad-headers:
  alias: header
  group: code
  filetypes: [".js"]
  targets:
    - "."
  excludes: []

# scripts/linting/code/no-trailing-whitespace.js
no-trailing-whitespace:
  alias: ws
  group: code
  filetypes: [".css", ".js", ".json", ".yaml"]
  targets: ["."]
  excludes: []

# scripts/linting/code/no-relative-paths.js
no-relative-paths:
  alias: paths
  group: code
  filetypes: [".js"]
  targets: ["."]
  excludes:
    - paths

# --- Validators ---

# scripts/linting/validators/mocha-path-validator.js
validate-mocha:
  alias: "mocha"
  group: "validators"

# --- Docs ---

# scripts/linting/docs/janitor.js
janitor:
  alias: "litter"
  group: "docs"
  targets: ["."]
  excludes: []

# scripts/linting/docs/librarian.js
librarian:
  alias: "index"
  group: "docs"
  docs:
    indexFile: docs/index.md
    scanRoot: docs
    filetypes: [".md"]
  plugins:
    marker: "plugins"
    indexFile: plugins/index.md
    scanRoot: plugins
    filetypes: [".md"]
    excludePatterns:
      - "plugins/**/index.md"
      - "plugins/**/*-example.md"
  scripts:
    marker: "scripts"
    indexFile: scripts/index.md
    scanRoot: scripts
    filetypes: [".js", ".sh"]
    excludePatterns:
      - "scripts/linting/**"
  linting:
    marker: "linting"
    indexFile: scripts/linting/index.md
    scanRoot: scripts/linting
    filetypes: [".js", ".yaml"]
    excludePatterns: []
  test:
    marker: "test"
    indexFile: test/index.md
    scanRoot:
      - test/analytics
      - test/config
    filetypes: [".js", ".json", ".yaml"]
    excludePatterns:
      - "test/archive/**"
  test-archive:
    marker: "test-archive"
    indexFile: test/archive/index.md
    scanRoot: test/archive
    filetypes: [".js", ".md"]
    excludePatterns: []
  paths:
    marker: "paths"
    indexFile: paths/index.md
    scanRoot: paths
    filetypes: [".js", ".yaml"]
    excludePatterns: []
  utils:
    marker: "utils"
    indexFile: src/utils/index.md
    scanRoot: src/utils
    filetypes: [".js"]
    excludePatterns: []

# scripts/linting/docs/postman.js
postman:
  alias: "links"
  group: "docs"
  targets:
   - "."
  filetypes: [".md", ".js"]
  skip_link_patterns:
    - "**/my[-_]*"
    - "**/my[-_]*/**"
    - "**/sample.md"
    - "**/index.js"
  excludes:
    - "test/archive/docs/checklist-*.md"
    - "test/archive/docs/audit-log.md"
    - "plugins/recipe-book/README.md"

# scripts/linting/docs/yaml.js
yaml:
  alias: "yaml-format"
  group: "docs"
  targets:
   - "test/runners/smoke/"
  filetypes: [".yaml"] # perhaps treat *.yml differently..
  field_order:
    # Lower numbers = higher priority
    name: -1
    description: 0
    test_id: 1
    base_command: 2
    tags: 3
    visual_focus: 4
    args: 6
    expect: 7
    expect_failure: 8
    expect_not: 9
    skip: 12
    debug: 13
    workflow: 19
    scenarios: 20
    visual_check: 21

# --- Harness Configuration ---
harness:
  continueOnError: false
  steps:
    # --- Code ---
    - key: 'no-trailing-whitespace'
      label: 'Code: Strip Trailing Whitespace'
      scriptPath: scripts/linting/code/no-trailing-whitespace.js
    - key: 'no-bad-headers'
      label: 'Code: Standardize File Headers'
      scriptPath: scripts/linting/code/no-bad-headers.js
    - key: 'no-console'
      label: 'Code: Check for console/chalk usage'
      scriptPath: scripts/linting/code/no-console.js
    - key: 'no-jsdoc'
      label: 'Code: Check for JSdoc comments'
      scriptPath: scripts/linting/code/no-jsdoc.js
    - key: 'no-relative-paths'
      label: 'Code: Check for relative paths'
      scriptPath: scripts/linting/code/no-relative-paths.js

    # --- Validators ---
    - key: 'validate-mocha'
      label: 'Validator: Check .mocharc.js paths'
      scriptPath: scripts/linting/validators/mocha-path-validator.js

    # --- Docs ---
    - key: 'librarian'
      label: 'Docs: Update Project Indices (Librarian)'
      scriptPath: scripts/linting/docs/librarian.js
    - key: 'postman'
      label: 'Docs: Check Markdown Links (Postman)'
      scriptPath: scripts/linting/docs/postman.js
    - key: 'janitor'
      label: 'Docs: Find Litter (Janitor)'
      scriptPath: scripts/linting/docs/janitor.js
    - key: 'yaml'
      label: 'Docs: Check YAML Format'
      scriptPath: scripts/linting/docs/yaml.js

    # --- Harness ---
    - key: 'eslint'
      label: 'ESLint'
      quiet: false
      command: 'eslint'
      defaultTargets: ['.']
